"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type L={id:string;lot_ref:string;order_id:string;grade:string;quantity_kg:number;status:string};type J={id:string;transport_ref:string;order_id:string;origin:string;destination:string;status:string};
export default function Logistics(){const [lots,setLots]=useState<L[]>([]);const [jobs,setJobs]=useState<J[]>([]);const [selected,setSelected]=useState<L|null>(null);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);async function load(){try{setLots(await api("/lots"));setJobs(await api("/transport-jobs"));}catch(e){setMsg(e instanceof Error?e.message:"Impossible de charger les données de transport.");}}useEffect(()=>{void load();},[]);
 async function transport(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(!selected||busy)return;const f=new FormData(e.currentTarget);const transporter=String(f.get("transporter_user_id")||"").trim();const origin=String(f.get("origin")||"").trim();const destination=String(f.get("destination")||"").trim();const vehicle=String(f.get("vehicle_ref")||"").trim();const driver=String(f.get("driver_name")||"").trim();if(!transporter||!origin||!destination){setMsg("Transporteur, origine et destination sont obligatoires.");return;}if(origin.toLocaleLowerCase("fr")==destination.toLocaleLowerCase("fr")){setMsg("L’origine et la destination doivent être différentes.");return;}setBusy(true);setMsg("");try{const d=await api("/transport-jobs",{method:"POST",body:JSON.stringify({order_id:selected.order_id,lot_ids:[selected.id],transporter_user_id:transporter,origin,destination,vehicle_ref:vehicle||null,driver_name:driver||null})});setMsg(`Transport créé ✓ ${d.transport_ref}`);setSelected(null);await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur lors de la création du transport.");}finally{setBusy(false);}}
 async function depart(j:J){if(busy)return;setBusy(true);setMsg("");try{await api(`/transport-jobs/${j.id}/depart`,{method:"POST"});setMsg("Départ enregistré ✓");await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur lors de l’enregistrement du départ.");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Transport" subtitle="Affectez chaque lot à un transporteur identifié avant le départ. Un lot physique ne peut être affecté qu’une seule fois." />{msg&&<div className="result">{msg}</div>}
 {selected&&<form className="agriForm" onSubmit={transport}><h2>Planifier {selected.lot_ref}</h2><p>{selected.quantity_kg.toLocaleString("fr-FR")} kg • Qualité {selected.grade}</p><label>Identifiant du transporteur<input name="transporter_user_id" required placeholder="UUID du compte TRANSPORTER"/></label><label>Origine<input name="origin" required placeholder="Village / Centre AGRI-CI"/></label><label>Destination<input name="destination" required placeholder="Lieu réel de livraison"/></label><label>Véhicule<input name="vehicle_ref" placeholder="Immatriculation ou référence"/></label><label>Conducteur<input name="driver_name" placeholder="Nom du conducteur"/></label><button disabled={busy}>{busy?"CRÉATION…":"CRÉER LE TRANSPORT"}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>ANNULER</button></form>}
 <h2 className="sectionTitle">Lots prêts</h2><section className="demandList">{lots.length?lots.map(l=><article className="demandCard" key={l.id}><span className="pill2">{l.status}</span><h2>{l.lot_ref}</h2><b>{l.quantity_kg.toLocaleString("fr-FR")} kg • Qualité {l.grade}</b>{l.status==="READY"&&<div className="commitActions"><button disabled={busy} onClick={()=>setSelected(l)}>PLANIFIER TRANSPORT</button></div>}</article>):<div className="empty">Aucun lot disponible.</div>}</section>
 <h2 className="sectionTitle">Transports</h2><section className="demandList">{jobs.length?jobs.map(j=><article className="demandCard" key={j.id}><span className="pill2">{j.status}</span><h2>{j.transport_ref}</h2><p>{j.origin} → {j.destination}</p>{j.status==="PLANNED"&&<div className="commitActions"><button disabled={busy} onClick={()=>depart(j)}>ENREGISTRER DÉPART</button></div>}</article>):<div className="empty">Aucun transport planifié.</div>}</section></main>}
