"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type Product={id:string;code:string;name_fr:string};
export default function Demand(){const [products,setProducts]=useState<Product[]>([]);const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);const [start,setStart]=useState("");const [end,setEnd]=useState("");
 useEffect(()=>{api("/products").then(setProducts).catch(e=>setMsg(e instanceof Error?e.message:"Impossible de charger les produits."));},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const f=new FormData(form);const grades=["A","B","C"].filter(g=>f.get(`g${g}`));const quantity=Number(f.get("quantity"));if(!Number.isFinite(quantity)||quantity<=0){setMsg("Indiquez une quantité recherchée supérieure à zéro.");return;}if(!start||!end||end<start){setMsg("La date de fin de livraison doit être égale ou postérieure à la date de début.");return;}if(grades.length===0){setMsg("Sélectionnez au moins une qualité acceptée : A, B ou C.");return;}setBusy(true);setMsg("");
 try{const d=await api("/demands",{method:"POST",body:JSON.stringify({product_code:f.get("product_code"),quantity_required_kg:quantity,delivery_start_date:start,delivery_end_date:end,target_price_xof_per_kg:f.get("price")?Number(f.get("price")):null,quality_grades:grades,destination_city:f.get("city")||null})});setMsg(`Demande publiée ✓ ${d.demand_ref}`);form.reset();setStart("");setEnd("");}
 catch(e){setMsg(e instanceof Error?e.message:"Erreur AGRI-CI");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Publier une demande" subtitle="Dites à AGRI-CI ce dont vous avez besoin. Le moteur cherchera et agrégera l’offre compatible."/>{msg&&<div className="result">{msg}</div>}
 <form className="agriForm" onSubmit={submit}><label>Produit<select name="product_code" required><option value="">Choisir</option>{products.map(p=><option key={p.id} value={p.code}>{p.name_fr}</option>)}</select></label><label>Quantité recherchée (kg)<input name="quantity" type="number" min="0.001" step="0.001" required placeholder="3000"/></label>
 <div className="two"><label>Livraison dès le<input name="start" type="date" required value={start} onChange={e=>{setStart(e.target.value);if(end&&e.target.value>end)setEnd("");}}/></label><label>Jusqu’au<input name="end" type="date" required min={start||undefined} value={end} onChange={e=>setEnd(e.target.value)}/></label></div>
 <label>Ville de destination<input name="city" placeholder="Abidjan"/></label><label>Prix cible / kg (XOF)<input name="price" type="number" min="1" placeholder="760"/></label><fieldset><legend>Qualité acceptée</legend><label className="check"><input type="checkbox" name="gA"/> A</label><label className="check"><input type="checkbox" name="gB"/> B</label><label className="check"><input type="checkbox" name="gC"/> C</label></fieldset><button disabled={busy}>{busy?"PUBLICATION…":"PUBLIER MA DEMANDE"}</button></form></main>}
