"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type Harvest={id:string;harvest_ref:string;estimated_quantity_kg:number;expected_start_date:string};
export default function Sell(){const [harvests,setHarvests]=useState<Harvest[]>([]);const [harvestId,setHarvestId]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);
 useEffect(()=>{api("/harvests").then(setHarvests).catch(e=>setMsg(e instanceof Error?e.message:"Impossible de charger les récoltes."));},[]);const selected=harvests.find(h=>h.id===harvestId);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const f=new FormData(e.currentTarget);const quantity=Number(f.get("quantity"));const priceRaw=String(f.get("price")||"").trim();const price=priceRaw?Number(priceRaw):null;if(!selected){setMsg("Choisissez d’abord une récolte annoncée.");return;}if(!Number.isFinite(quantity)||quantity<=0||quantity>selected.estimated_quantity_kg){setMsg(`La quantité doit être supérieure à 0 et ne peut pas dépasser les ${selected.estimated_quantity_kg.toLocaleString("fr-FR")} kg annoncés pour cette récolte.`);return;}if(price!==null&&(!Number.isFinite(price)||price<=0)){setMsg("Le prix souhaité doit être supérieur à 0 XOF/kg.");return;}setBusy(true);setMsg("");
 try{const d=await api("/offers",{method:"POST",body:JSON.stringify({harvest_id:selected.id,quantity_kg:quantity,asking_price_xof_per_kg:price,quality_grade:f.get("grade")||null})});setMsg(`Offre créée ✓ ${d.offer_ref}`);(e.currentTarget as HTMLFormElement).reset();setHarvestId("");}catch(e){const text=e instanceof Error?e.message:"Erreur AGRI-CI";setMsg(text.includes("OFFER_EXCEEDS_HARVEST_AVAILABLE_QUANTITY")?"Cette récolte est déjà engagée dans une ou plusieurs offres. Réduisez la quantité à vendre.":text);}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Vendre" subtitle="Choisissez une récolte déjà annoncée et indiquez la quantité que vous souhaitez proposer au marché."/>{msg&&<div className="result">{msg}</div>}
 <form className="agriForm" onSubmit={submit}><label>Récolte<select name="harvest_id" required value={harvestId} onChange={e=>setHarvestId(e.target.value)}><option value="">Choisir</option>{harvests.map(h=><option key={h.id} value={h.id}>{h.harvest_ref} — {h.estimated_quantity_kg.toLocaleString("fr-FR")} kg — {h.expected_start_date}</option>)}</select></label>
 {selected&&<><p>Récolte annoncée : <b>{selected.estimated_quantity_kg.toLocaleString("fr-FR")} kg</b></p><small>AGRI-CI vérifie aussi au moment de la vente les quantités déjà engagées dans d’autres offres de cette récolte.</small></>}<label>Quantité à vendre (kg)<input name="quantity" type="number" min="0.001" max={selected?.estimated_quantity_kg} step="0.001" required/></label><label>Prix souhaité / kg (XOF)<input name="price" type="number" min="1" step="1"/></label>
 <label>Qualité<select name="grade"><option value="">À déterminer</option><option value="A">A</option><option value="B">B</option><option value="C">C</option></select></label><button disabled={busy}>{busy?"MISE EN VENTE…":"METTRE EN VENTE"}</button></form></main>}
