"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type J={id:string;transport_ref:string;origin:string;destination:string;status:string};
export default function Delivery(){const [jobs,setJobs]=useState<J[]>([]);const [selected,setSelected]=useState<J|null>(null);const [qty,setQty]=useState("");const [receivedBy,setReceivedBy]=useState("");const [msg,setMsg]=useState("Chargement…");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);
 async function load(){if(loading)return;setLoading(true);setFailed(false);try{const data=await api("/transport-jobs");const rows=Array.isArray(data)?data:[];setJobs(rows);setMsg(rows.length?"":"Aucun transport à livrer pour le moment.");}catch(e){setJobs([]);setFailed(true);setMsg(e instanceof Error?e.message:"Impossible de charger les transports.");}finally{setLoading(false);}}useEffect(()=>{void load();},[]);
 function choose(j:J){if(busy)return;setSelected(j);setQty("");setReceivedBy("");setMsg("");}
 async function deliver(e:React.FormEvent){e.preventDefault();if(!selected||busy)return;const quantity=Number(qty);if(!Number.isFinite(quantity)||quantity<=0){setMsg("Indiquez une quantité livrée supérieure à zéro.");return;}if(!receivedBy.trim()){setMsg("Indiquez la personne qui a reçu la livraison.");return;}setBusy(true);setMsg("");try{const d=await api("/deliveries",{method:"POST",body:JSON.stringify({transport_job_id:selected.id,delivered_quantity_kg:quantity,received_by:receivedBy.trim()})});setMsg(`Livraison enregistrée ✓ ${d.delivery_ref}`);setSelected(null);setQty("");setReceivedBy("");await load();}catch(e){setMsg(e instanceof Error?e.message:"Impossible d’enregistrer la livraison.");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Livraison" subtitle="Confirmez la quantité réellement reçue. AGRI-CI utilisera ensuite les quantités livrées pour préparer les règlements." />{msg&&<div className="result">{msg}{failed&&<div className="commitActions"><button disabled={loading||busy} onClick={()=>void load()}>{loading?"ACTUALISATION…":"RÉESSAYER"}</button></div>}</div>}
 {selected&&<form className="agriForm" onSubmit={deliver}><h2>{selected.transport_ref}</h2><p>{selected.origin} → {selected.destination}</p><label>Quantité réellement livrée (kg)<input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0.001" step="0.001" required/></label><label>Reçu par<input value={receivedBy} onChange={e=>setReceivedBy(e.target.value)} required placeholder="Nom du réceptionnaire"/></label><button disabled={busy}>{busy?"ENREGISTREMENT…":"ENREGISTRER LA LIVRAISON"}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>ANNULER</button></form>}
 <section className="demandList">{jobs.map(j=><article className="demandCard" key={j.id}><span className="pill2">{j.status}</span><h2>{j.transport_ref}</h2><p>{j.origin} → {j.destination}</p>{j.status==="IN_TRANSIT"&&<div className="commitActions"><button disabled={busy||loading} onClick={()=>choose(j)}>CONFIRMER LIVRAISON</button></div>}</article>)}</section></main>}
