"use client";
import {useEffect,useState} from "react";import {useParams} from "next/navigation";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type Match={offer_ref:string;farmer_name:string;compatible_quantity_kg:number;asking_price_xof_per_kg?:number;quality_grade?:string;total_score:number};
type Agg={id:string;ref:string;target_quantity_kg:number;proposed_quantity_kg:number;accepted_quantity_kg:number;status:string;members?:any[]};
type Mine={id:string;aggregation_id?:string|null};
export default function DemandDetail(){const {id}=useParams<{id:string}>();const [matches,setMatches]=useState<Match[]>([]);const [agg,setAgg]=useState<Agg|null>(null);const [msg,setMsg]=useState("Chargement…");const [busy,setBusy]=useState(false);
 useEffect(()=>{let active=true;(async()=>{try{const mine:Mine[]=await api("/demands/mine");const current=mine.find(d=>d.id===id);if(current?.aggregation_id){const full=await api(`/aggregations/${current.aggregation_id}`);if(active)setAgg(full);}if(active)setMsg("");}catch(e){if(active)setMsg(e instanceof Error?e.message:"Erreur");}})();return()=>{active=false};},[id]);
 async function match(){setBusy(true);try{const d=await api(`/demands/${id}/match`,{method:"POST"});setMatches(d.matches);setMsg(`${d.compatible_quantity_kg} kg compatibles trouvés.`);}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
 async function aggregate(){setBusy(true);try{const d=await api(`/demands/${id}/aggregate`,{method:"POST"});const full=await api(`/aggregations/${d.aggregation_id}`);setAgg(full);setMsg("Propositions envoyées aux producteurs.");}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
 async function refresh(){if(!agg)return;setBusy(true);try{setAgg(await api(`/aggregations/${agg.id}`));setMsg("Agrégation actualisée.");}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
 async function createOrder(){if(!agg)return;setBusy(true);try{const d=await api(`/orders/from-aggregation/${agg.id}`,{method:"POST"});setMsg(`Commande ferme créée ✓ ${d.order_ref}`);}catch(e){setMsg(e instanceof Error?e.message:"Commande impossible");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Matching & agrégation" subtitle="AGRI-CI recherche plusieurs offres compatibles pour constituer votre quantité."/>
 <div className="stepActions">{!agg&&<button disabled={busy} onClick={match}>1. LANCER LE MATCHING</button>}{!agg&&<button disabled={busy||!matches.length} onClick={aggregate}>2. LANCER L’AGRÉGATION</button>}{agg&&<button disabled={busy} onClick={refresh}>ACTUALISER LES CONFIRMATIONS</button>}</div>
 {msg&&<div className="result">{msg}</div>}
 {!agg&&matches.length>0&&<section><h2 className="sectionTitle">Producteurs compatibles</h2><div className="demandList">{matches.map((m,i)=><article className="demandCard" key={i}><span className="score">{Math.round(m.total_score)}/100</span><h2>{m.farmer_name}</h2><b>{m.compatible_quantity_kg} kg</b><p>{m.offer_ref} • Qualité {m.quality_grade||"à confirmer"}</p><small>{m.asking_price_xof_per_kg?`${m.asking_price_xof_per_kg} XOF/kg`:"Prix à convenir"}</small></article>)}</div></section>}
 {agg&&<section><h2 className="sectionTitle">Agrégation {agg.ref}</h2><div className="progressCard"><b>{agg.accepted_quantity_kg} / {agg.target_quantity_kg} kg confirmés</b><div className="bar"><i style={{width:`${Math.min(100,100*agg.accepted_quantity_kg/agg.target_quantity_kg)}%`}}/></div><span>{agg.status}</span></div>
 {agg.accepted_quantity_kg>=agg.target_quantity_kg&&<button disabled={busy} className="orderGate" onClick={createOrder}>CRÉER LA COMMANDE FERME</button>}
 <div className="demandList">{agg.members?.map((m,i)=><article className="demandCard" key={i}><h2>{m.farmer_name}</h2><b>{m.proposed_quantity_kg} kg proposés</b><p>{m.offer_ref}</p><span className="pill2">{m.commitment_status}</span></article>)}</div></section>}</main>}
