"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type C={id:string;commitment_ref:string;quantity_kg:number;status:string;product_name:string;destination_city?:string;target_price_xof_per_kg?:number;asking_price_xof_per_kg?:number;expires_at:string};
export default function Commitments(){const [rows,setRows]=useState<C[]>([]);const [msg,setMsg]=useState("Chargement…");const [busyId,setBusyId]=useState<string|null>(null);
 async function load(){try{const data=await api("/commitments");setRows(data);setMsg(data.length?"":"Aucune proposition AGRI-CI.");}catch(e){setMsg(e instanceof Error?e.message:"Impossible de charger les propositions.");}}
 useEffect(()=>{void load();},[]);
 async function act(c:C,action:"accept"|"decline"){if(busyId||c.status!=="PENDING")return;if(new Date(c.expires_at).getTime()<=Date.now()){setMsg("Cette proposition a expiré. Actualisez la page pour obtenir son état à jour.");return;}setBusyId(c.id);setMsg("");try{await api(`/commitments/${c.id}/${action}`,{method:"POST"});setMsg(action==="accept"?"Proposition acceptée. La quantité est maintenant engagée dans l’agrégation.":"Proposition refusée. AGRI-CI peut chercher une offre de remplacement.");await load();}catch(e){setMsg(e instanceof Error?e.message:"Impossible d’enregistrer votre décision.");}finally{setBusyId(null);}}
 return <main className="workflow"><WorkflowHeader title="Propositions AGRI-CI" subtitle="Répondez aux demandes auxquelles votre offre peut contribuer."/>
 {msg&&<div className="result">{msg}</div>}<section className="demandList">{rows.map(c=>{const expired=new Date(c.expires_at).getTime()<=Date.now();return <article className="demandCard" key={c.id}><span className="pill2">{expired&&c.status==="PENDING"?"EXPIRÉE":c.status}</span><h2>{c.product_name}</h2><b>{c.quantity_kg.toLocaleString("fr-FR")} kg proposés</b><p>Destination : {c.destination_city||"à confirmer"}</p>
 <small>{c.asking_price_xof_per_kg?`Votre prix : ${Number(c.asking_price_xof_per_kg).toLocaleString("fr-FR")} XOF/kg`:"Prix à confirmer"} • échéance {new Date(c.expires_at).toLocaleString("fr-FR")}</small>
 {c.status==="PENDING"&&!expired&&<div className="commitActions"><button disabled={busyId!==null} onClick={()=>act(c,"accept")}>{busyId===c.id?"TRAITEMENT…":"ACCEPTER"}</button><button disabled={busyId!==null} className="decline" onClick={()=>act(c,"decline")}>{busyId===c.id?"TRAITEMENT…":"REFUSER"}</button></div>}</article>})}</section></main>}
