"use client";
import {useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type Prepared={payment_ref?:string;status?:string;net_amount_xof?:number;delivered_quantity_kg?:number;gross_amount_xof?:number};
const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
export default function Payments(){const [msg,setMsg]=useState("");const [rows,setRows]=useState<Prepared[]>([]);const [busy,setBusy]=useState(false);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;const form=e.currentTarget;const f=new FormData(form);const orderId=String(f.get("order_id")||"").trim();const provider=String(f.get("provider")||"").trim();const price=Number(f.get("price"));const transport=Number(f.get("transport")||0);const service=Number(f.get("service")||0);const other=Number(f.get("other")||0);
 if(!UUID.test(orderId)){setMsg("Indiquez l’identifiant technique valide de la commande.");return;}if(!provider){setMsg("Indiquez le prestataire de paiement autorisé.");return;}if(!Number.isFinite(price)||price<=0||[transport,service,other].some(v=>!Number.isFinite(v)||v<0)){setMsg("Vérifiez le prix et les coûts avant de préparer les règlements.");return;}
 setBusy(true);setMsg("");try{const d=await api(`/payments/orders/${orderId}/prepare`,{method:"POST",body:JSON.stringify({price_xof_per_kg:price,transport_xof:transport,service_xof:service,other_xof:other,provider})});const prepared=Array.isArray(d?.prepared)?d.prepared:[];setRows(prepared);setMsg(`${prepared.length} règlement(s) préparé(s) sur les quantités livrées et non encore réglées.`);}catch(e){setRows([]);setMsg(e instanceof Error?e.message:"Impossible de préparer les règlements.");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Préparer les règlements" subtitle="AGRI-CI calcule le brut sur la quantité réellement livrée, répartit les coûts autorisés et prépare le net dû à chaque producteur."/>
 <form className="agriForm" onSubmit={submit}><label>Identifiant technique de la commande<input name="order_id" required placeholder="UUID de la commande"/></label><label>Prix commercial (XOF/kg)<input name="price" type="number" min="1" step="1" required placeholder="Prix convenu"/></label>
 <label>Transport total (XOF)<input name="transport" type="number" min="0" step="1" defaultValue="0"/></label><label>Service AGRI-CI total (XOF)<input name="service" type="number" min="0" step="1" defaultValue="0"/></label>
 <label>Autres coûts autorisés (XOF)<input name="other" type="number" min="0" step="1" defaultValue="0"/></label><label>Prestataire<input name="provider" required placeholder="Prestataire de paiement autorisé"/></label>
 <p className="notice">Les coûts sont à zéro par défaut. L’opérateur doit saisir uniquement les montants réellement autorisés pour cette commande.</p><button disabled={busy}>{busy?"PRÉPARATION…":"PRÉPARER LES RÈGLEMENTS"}</button></form>{msg&&<div className="result">{msg}</div>}
 <section className="demandList">{rows.map((p,i)=><article className="demandCard" key={p.payment_ref||i}><span className="pill2">{p.status||"PRÉPARÉ"}</span><h2>{p.payment_ref||"Règlement"}</h2><b>{Number(p.net_amount_xof||0).toLocaleString("fr-FR")} XOF net</b><p>{Number(p.delivered_quantity_kg||0).toLocaleString("fr-FR")} kg livrés • brut {Number(p.gross_amount_xof||0).toLocaleString("fr-FR")} XOF</p></article>)}</section></main>}
