"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type P={id:string;payment_ref:string;order_id:string;gross_amount_xof:number;deductions_xof:number;net_amount_xof:number;settled_quantity_kg?:number|null;provider:string;status:string};
const statusLabel:Record<string,string>={PENDING:"En attente",PROCESSING:"En traitement",SUCCESS:"Payé",FAILED:"Échec",REFUNDED:"Remboursé",DISPUTED:"Contesté"};
export default function Money(){const [rows,setRows]=useState<P[]>([]);const [msg,setMsg]=useState("Chargement…");const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);
 async function load(){if(loading)return;setLoading(true);setFailed(false);setMsg("Chargement…");try{const data=await api("/payments/farmer/me");const payments=Array.isArray(data)?data:[];setRows(payments);setMsg(payments.length?"":"Aucun règlement enregistré pour le moment.");}catch(e){setRows([]);setFailed(true);setMsg(e instanceof Error?e.message:"Impossible de charger vos règlements.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 return <main className="workflow"><WorkflowHeader title="Mon argent" subtitle="Suivez uniquement vos règlements réels : montant brut, coûts autorisés, net producteur et statut du prestataire de paiement." />{msg&&<div className="result">{msg}{failed&&<div className="commitActions"><button disabled={loading} onClick={()=>void load()}>{loading?"ACTUALISATION…":"RÉESSAYER"}</button></div>}</div>}
 {rows.map(p=><section key={p.id}><div className="moneyHero"><span>{p.payment_ref} • {statusLabel[p.status]||p.status}</span><b>{Number(p.net_amount_xof).toLocaleString("fr-FR")} XOF</b><small>Brut {Number(p.gross_amount_xof).toLocaleString("fr-FR")} XOF • Déductions {Number(p.deductions_xof).toLocaleString("fr-FR")} XOF{p.settled_quantity_kg!=null?` • ${Number(p.settled_quantity_kg).toLocaleString("fr-FR")} kg réglés`:""}</small></div><p className="notice">Prestataire : {p.provider}. AGRI-CI trace le règlement sans détenir les fonds.</p></section>)}</main>}
