"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type Plot={id:string;name:string;plot_ref:string}; type Product={id:string;code:string;name_fr:string};
export default function Harvest(){const [plots,setPlots]=useState<Plot[]>([]);const [products,setProducts]=useState<Product[]>([]);const [msg,setMsg]=useState("Chargement…");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);
 async function load(){if(loading)return;setLoading(true);setFailed(false);setMsg("Chargement…");try{const [plotData,productData]=await Promise.all([api("/plots"),api("/products")]);const nextPlots=Array.isArray(plotData)?plotData:[];const nextProducts=Array.isArray(productData)?productData:[];setPlots(nextPlots);setProducts(nextProducts);if(!nextPlots.length)setMsg("Aucune parcelle disponible. Enregistrez d’abord une parcelle avant d’annoncer une récolte.");else if(!nextProducts.length)setMsg("Aucun produit agricole disponible pour le moment.");else setMsg("");}catch(e){setPlots([]);setProducts([]);setFailed(true);setMsg(e instanceof Error?e.message:"Impossible de charger les données nécessaires à l’annonce de récolte.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();if(busy||loading)return;const form=e.currentTarget;const f=new FormData(form);const quantity=Number(f.get("quantity"));const start=String(f.get("start")||"");const end=String(f.get("end")||"");
 if(!plots.length||!products.length){setMsg("Les parcelles et les produits doivent être chargés avant d’annoncer une récolte.");return;}if(!Number.isFinite(quantity)||quantity<=0){setMsg("La quantité estimée doit être supérieure à 0 kg.");return;}if(!start||!end||end<start){setMsg("La date de fin prévue ne peut pas être antérieure à la date de début.");return;}setBusy(true);setMsg("");
 try{const d=await api("/harvests",{method:"POST",body:JSON.stringify({plot_id:f.get("plot_id"),product_code:f.get("product_code"),expected_start_date:start,expected_end_date:end,estimated_quantity_kg:quantity})});setMsg(`Récolte annoncée ✓ ${d.harvest_ref}`);form.reset();}catch(e){setMsg(e instanceof Error?e.message:"Erreur AGRI-CI");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Ma prochaine récolte" subtitle="Annoncez tôt. AGRI-CI peut chercher le marché avant la récolte."/>
 {msg&&<div className="result">{msg}{failed&&<div className="commitActions"><button disabled={loading||busy} onClick={()=>void load()}>{loading?"ACTUALISATION…":"RÉESSAYER"}</button></div>}</div>}
 <form className="agriForm" onSubmit={submit}><label>Produit<select name="product_code" required disabled={loading||busy}><option value="">Choisir</option>{products.map(p=><option key={p.id} value={p.code}>{p.name_fr}</option>)}</select></label>
 <label>Parcelle<select name="plot_id" required disabled={loading||busy}><option value="">Choisir ma parcelle</option>{plots.map(p=><option key={p.id} value={p.id}>{p.name} — {p.plot_ref}</option>)}</select></label>
 <label>Quantité estimée (kg)<input name="quantity" type="number" min="0.001" step="0.001" required placeholder="Quantité réellement estimée" disabled={loading||busy}/></label>
 <div className="two"><label>Début prévu<input name="start" type="date" required disabled={loading||busy}/></label><label>Fin prévue<input name="end" type="date" required disabled={loading||busy}/></label></div>
 <button disabled={busy||loading||!plots.length||!products.length}>{busy?"ENREGISTREMENT…":"ANNONCER MA RÉCOLTE"}</button></form></main>}
