"use client";
import {useEffect,useState} from "react";
import WorkflowHeader from "@/components/WorkflowHeader";
import {api} from "@/lib/api";
type Allocation={allocation_id:string;order_ref:string;product_name:string;farmer_name:string;allocated_quantity_kg:number;collected_quantity_kg:number;remaining_quantity_kg:number};
export default function Collection(){
 const [rows,setRows]=useState<Allocation[]>([]);const [selected,setSelected]=useState<Allocation|null>(null);const [qty,setQty]=useState("");const [location,setLocation]=useState("");const [msg,setMsg]=useState("Chargement…");const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(false);const [failed,setFailed]=useState(false);
 async function load(){if(loading)return;setLoading(true);setFailed(false);try{const data=await api("/collection/pending");const list=Array.isArray(data)?data:[];setRows(list);setMsg(list.length?"":"Aucune collecte en attente.");}catch(e){setRows([]);setFailed(true);setMsg(e instanceof Error?e.message:"Impossible de charger les collectes en attente.");}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 function choose(a:Allocation){if(busy||loading)return;setSelected(a);setQty(String(a.remaining_quantity_kg));setLocation("");setMsg("");}
 async function submit(e:React.FormEvent){e.preventDefault();if(!selected||busy||loading)return;const quantity=Number(qty);const collectionPoint=location.trim();if(!Number.isFinite(quantity)||quantity<=0||quantity>selected.remaining_quantity_kg){setMsg(`La quantité reçue doit être supérieure à 0 et ne pas dépasser ${selected.remaining_quantity_kg.toLocaleString("fr-FR")} kg.`);return;}if(!collectionPoint){setMsg("Le point réel de collecte est obligatoire pour assurer la traçabilité.");return;}setBusy(true);setMsg("");try{const d=await api("/collection",{method:"POST",body:JSON.stringify({order_allocation_id:selected.allocation_id,received_quantity_kg:quantity,location_name:collectionPoint})});setMsg(`Collecte enregistrée ✓ ${d.collection_ref}`);setSelected(null);setQty("");setLocation("");await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur lors de l’enregistrement de la collecte.");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Collecte" subtitle="Enregistrer le poids réellement reçu de chaque producteur et le point réel de collecte avant le contrôle qualité." />{msg&&<div className="result">{msg}{failed&&<div className="commitActions"><button disabled={loading||busy} onClick={()=>void load()}>{loading?"ACTUALISATION…":"RÉESSAYER"}</button></div>}</div>}
 {selected&&<form className="agriForm" onSubmit={submit}><h2>Recevoir {selected.farmer_name}</h2><p>{selected.product_name} • commande {selected.order_ref} • {selected.remaining_quantity_kg.toLocaleString("fr-FR")} kg restent à recevoir</p><label>Quantité réellement reçue (kg)<input type="number" min="0.001" max={selected.remaining_quantity_kg} step="0.001" value={qty} onChange={e=>setQty(e.target.value)} required/></label><label>Point réel de collecte<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Village, coopérative ou centre de collecte" required/></label><button disabled={busy||loading}>{busy?"ENREGISTREMENT…":"ENREGISTRER LA COLLECTE"}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>ANNULER</button></form>}
 <section className="demandList">{rows.map(a=><article className="demandCard" key={a.allocation_id}><span className="pill2">{a.order_ref}</span><h2>{a.farmer_name}</h2><b>{a.product_name}</b><p>{a.allocated_quantity_kg.toLocaleString("fr-FR")} kg prévus • {a.collected_quantity_kg.toLocaleString("fr-FR")} kg reçus</p><p><strong>{a.remaining_quantity_kg.toLocaleString("fr-FR")} kg à recevoir</strong></p><div className="commitActions"><button disabled={busy||loading} onClick={()=>choose(a)}>ENREGISTRER LA RÉCEPTION</button></div></article>)}</section></main>;
}
