"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type C={collection_id:string;collection_ref:string;order_id:string;order_ref:string;product_name:string;received_quantity_kg:number;graded_quantity_kg:number;remaining_to_grade_kg:number;location_name?:string;quality_checks:{id:string;grade:string;quantity_kg:number}[]};
export default function Quality(){const [rows,setRows]=useState<C[]>([]);const [selected,setSelected]=useState<C|null>(null);const [grade,setGrade]=useState("A");const [qty,setQty]=useState("");const [msg,setMsg]=useState("");const [busy,setBusy]=useState(false);async function load(){try{setRows(await api("/collection/operations"));}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}}useEffect(()=>{load();},[]);
 function choose(c:C){setSelected(c);setGrade("A");setQty(String(c.remaining_to_grade_kg));setMsg("");}
 async function submitGrade(e:React.FormEvent){e.preventDefault();if(!selected)return;const quantity=Number(qty);if(!Number.isFinite(quantity)||quantity<=0||quantity>selected.remaining_to_grade_kg){setMsg(`La quantité doit être supérieure à 0 et ne pas dépasser ${selected.remaining_to_grade_kg} kg.`);return;}setBusy(true);setMsg("");try{await api(`/collection/${selected.collection_id}/quality`,{method:"POST",body:JSON.stringify({grade,quantity_kg:quantity})});setMsg("Qualité enregistrée ✓");setSelected(null);await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
 async function lot(c:C,qid:string){setBusy(true);try{const d=await api("/lots",{method:"POST",body:JSON.stringify({order_id:c.order_id,quality_check_ids:[qid]})});setMsg(`Lot créé ✓ ${d.lot_ref}`);await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}finally{setBusy(false);}}
 return <main className="workflow"><WorkflowHeader title="Qualité & lots" subtitle="Le poids réellement reçu est classé avant d’entrer dans la chaîne logistique." />{msg&&<div className="result">{msg}</div>}
 {selected&&<form className="agriForm" onSubmit={submitGrade}><h2>Classer {selected.collection_ref}</h2><p>{selected.product_name} • {selected.remaining_to_grade_kg.toLocaleString("fr-FR")} kg restent à classer</p><label>Classe qualité<select value={grade} onChange={e=>setGrade(e.target.value)}><option value="A">A</option><option value="B">B</option><option value="C">C</option></select></label><label>Quantité à classer (kg)<input value={qty} onChange={e=>setQty(e.target.value)} type="number" min="0.001" max={selected.remaining_to_grade_kg} step="0.001" required/></label><button disabled={busy}>{busy?"ENREGISTREMENT…":"ENREGISTRER LA QUALITÉ"}</button><button type="button" disabled={busy} onClick={()=>setSelected(null)}>ANNULER</button></form>}
 <section className="demandList">{rows.map(c=><article className="demandCard" key={c.collection_id}><span className="pill2">{c.collection_ref}</span><h2>{c.product_name}</h2><b>{c.received_quantity_kg.toLocaleString("fr-FR")} kg reçus</b><p>{c.graded_quantity_kg.toLocaleString("fr-FR")} kg classés • {c.remaining_to_grade_kg.toLocaleString("fr-FR")} kg à classer</p>{c.location_name&&<p>{c.location_name}</p>}
 {c.remaining_to_grade_kg>0&&<div className="commitActions"><button disabled={busy} onClick={()=>choose(c)}>CLASSER A/B/C</button></div>}
 {c.quality_checks.map(q=><div className="qualityLine" key={q.id}><span>Qualité {q.grade}</span><b>{q.quantity_kg.toLocaleString("fr-FR")} kg</b><button disabled={busy} onClick={()=>lot(c,q.id)}>CRÉER LOT</button></div>)}</article>)}</section></main>}
