"use client";
import {useEffect,useState} from "react";import WorkflowHeader from "@/components/WorkflowHeader";import {api} from "@/lib/api";
type C={collection_id:string;collection_ref:string;order_id:string;order_ref:string;product_name:string;received_quantity_kg:number;graded_quantity_kg:number;remaining_to_grade_kg:number;location_name?:string;quality_checks:{id:string;grade:string;quantity_kg:number}[]};
export default function Quality(){const [rows,setRows]=useState<C[]>([]);const [msg,setMsg]=useState("");async function load(){try{setRows(await api("/collection/operations"));}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}}useEffect(()=>{load();},[]);
 async function grade(c:C){const grade=prompt("Classe qualité : A, B ou C","A");const qty=prompt(`Quantité à classer (max ${c.remaining_to_grade_kg} kg)`);if(!grade||!qty)return;try{await api(`/collection/${c.collection_id}/quality`,{method:"POST",body:JSON.stringify({grade:grade.toUpperCase(),quantity_kg:Number(qty)})});setMsg("Qualité enregistrée ✓");await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}}
 async function lot(c:C,qid:string){try{const d=await api("/lots",{method:"POST",body:JSON.stringify({order_id:c.order_id,quality_check_ids:[qid]})});setMsg(`Lot créé ✓ ${d.lot_ref}`);await load();}catch(e){setMsg(e instanceof Error?e.message:"Erreur");}}
 return <main className="workflow"><WorkflowHeader title="Qualité & lots" subtitle="Le poids reçu est classé avant d’entrer dans la chaîne logistique." />{msg&&<div className="result">{msg}</div>}
 <section className="demandList">{rows.map(c=><article className="demandCard" key={c.collection_id}><span className="pill2">{c.collection_ref}</span><h2>{c.product_name}</h2><b>{c.received_quantity_kg} kg reçus</b><p>{c.graded_quantity_kg} kg classés • {c.remaining_to_grade_kg} kg à classer</p>
 {c.remaining_to_grade_kg>0&&<div className="commitActions"><button onClick={()=>grade(c)}>CLASSER A/B/C</button></div>}
 {c.quality_checks.map(q=><div className="qualityLine" key={q.id}><span>Qualité {q.grade}</span><b>{q.quantity_kg} kg</b><button onClick={()=>lot(c,q.id)}>CRÉER LOT</button></div>)}</article>)}</section></main>}